package org.brms.hhinsurance;
global java.util.List AccreditedBuilder;
global java.util.List AccreditedBuilderName;

rule "checking accreditedbuilder is yes"

when
    Accreditedbuilder(accredited.equalsIgnoreCase("yes") || accreditedSupplement.equalsIgnoreCase("yes"))
then
    AccreditedBuilder.clear();
    AccreditedBuilder.add("1");
    AccreditedBuilderName.clear();
    AccreditedBuilderName.add("KB Homes");
    System.out.println("accreditedbuilderNames rule 1");
end

rule "checking accreditedbuilder supplementary is no"

when
    Accreditedbuilder(accreditedSupplement.equalsIgnoreCase("no"))
then
    AccreditedBuilder.clear();
    AccreditedBuilder.add("0");
    AccreditedBuilderName.clear();
    AccreditedBuilderName.add("");
    System.out.println("accreditedbuilderNames rule 2");
end

