package org.brms.hhinsurance;
global java.util.List flatRoofEligibility;

rule "Flat roof Percentage: less than 10 %"
    when
        FlatRoofPolicy(roofPercent.equalsIgnoreCase("0to10") || roofPercent.equals(""))
    then
        flatRoofEligibility.add("American Integrity");
        flatRoofEligibility.add("American Strategic");
        flatRoofEligibility.add("Anchor");
        flatRoofEligibility.add("Bankers");
        flatRoofEligibility.add("Cabrillo");
        flatRoofEligibility.add("Centauri");
        flatRoofEligibility.add("Edison");
        flatRoofEligibility.add("FedNat");
        flatRoofEligibility.add("Florida Peninsula");
        flatRoofEligibility.add("Frontline");
        flatRoofEligibility.add("Geovera");
        flatRoofEligibility.add("Heritage");
        flatRoofEligibility.add("Homeowners Choice");
        flatRoofEligibility.add("Monarch");
        flatRoofEligibility.add("Olympus");
        flatRoofEligibility.add("Prepared");
        flatRoofEligibility.add("Service (SageSure)");
        flatRoofEligibility.add("Southern Oak");
        flatRoofEligibility.add("Swyfft");
        flatRoofEligibility.add("St. Johns");
        flatRoofEligibility.add("The Hearth");
        flatRoofEligibility.add("TypTap Home");
        flatRoofEligibility.add("United");
        flatRoofEligibility.add("Universal PC");
        flatRoofEligibility.add("Velocity");
        flatRoofEligibility.add("Western World");
end
rule "Flat roof Percentage: 11 to 25%"
    when
        FlatRoofPolicy(roofPercent.equalsIgnoreCase("11to25"))
    then
        flatRoofEligibility.add("American Integrity");
        flatRoofEligibility.add("Bankers");
        flatRoofEligibility.add("Edison");
        flatRoofEligibility.add("FedNat");
        flatRoofEligibility.add("Florida Peninsula");
        flatRoofEligibility.add("Frontline");
        flatRoofEligibility.add("Geovera");
        flatRoofEligibility.add("Heritage");
        flatRoofEligibility.add("Homeowners Choice");
        flatRoofEligibility.add("Monarch");
        flatRoofEligibility.add("Olympus");
        flatRoofEligibility.add("Prepared");
        flatRoofEligibility.add("Service (SageSure)");
        flatRoofEligibility.add("Southern Oak");
        flatRoofEligibility.add("Swyfft");
        flatRoofEligibility.add("St. Johns");
        flatRoofEligibility.add("The Hearth");
        flatRoofEligibility.add("TypTap Home");
        flatRoofEligibility.add("Universal PC");
        flatRoofEligibility.add("Velocity");
        flatRoofEligibility.add("Western World");
end

rule "Flat roof Percentage: 26% or more"
    when
        FlatRoofPolicy(roofPercent.equalsIgnoreCase("26to100"))
    then
        flatRoofEligibility.add("Bankers");
        flatRoofEligibility.add("Edison");
        flatRoofEligibility.add("FedNat");
        flatRoofEligibility.add("Florida Peninsula");
        flatRoofEligibility.add("Geovera");
        flatRoofEligibility.add("Frontline");
        flatRoofEligibility.add("Homeowners Choice");
        flatRoofEligibility.add("Monarch");
        flatRoofEligibility.add("Prepared");
        flatRoofEligibility.add("Service (SageSure)");
        flatRoofEligibility.add("Southern Oak");
        flatRoofEligibility.add("Swyfft");
        flatRoofEligibility.add("The Hearth");
        flatRoofEligibility.add("TypTap Home");
        flatRoofEligibility.add("Universal PC");
        flatRoofEligibility.add("Velocity");
        flatRoofEligibility.add("Western World");
end