package org.brms.hhinsurance;
global java.util.List HO3AnimalLiability;
global java.util.List HO6AnimalLiability;

rule "carrier for which $25 and sublimit of $50000 is available for HO3"
when
    AnimalLiability(carrier in ("American Strategic","Monarch","Cabrillo","FedNat","Florida Specialty","Heritage","Service (SageSure)","United"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $25 ; Sublimit - $50,000");
end

rule "carrier for which $25 and sublimit of $25000 is available for HO3"
when
    AnimalLiability(carrier in ("Anchor","Bankers","Centauri","Edison","Florida Peninsula","Southern Oak","Velocity"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $25 ; Sublimit - $25,000");
end

rule "carrier for which $50 and sublimit of $50000 is available for HO3"
when
    AnimalLiability(carrier in ("Olympus","Prepared","St. Johns"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $50 ; Sublimit - $50,000");
end

rule "carrier which is included and sublimit of $50000 is available for HO3"
when
    AnimalLiability(carrier in ("Swyfft"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Included ; Sublimit - $50,000");
end

rule "carrier for which $30 and sublimit of $25000 is available for HO3"
when
    AnimalLiability(carrier in ("Frontline"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $30 ; Sublimit - $25,000");
end

rule "carrier not available in Animal Liability for HO3"
when
    AnimalLiability(carrier in ("Geovera","Homeowners Choice","TypTap Home","Universal PC"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Not Available");
end

rule "carrier for which $25 and sublimit of CoverageE is available for HO3"
when
    c:AnimalLiability(carrier in ("Western World"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $25 ; Coverage - "+c.getCoverageE());
end

rule "carrier for which $50 and sublimit of CoverageE is available for HO3"
when
    c:AnimalLiability(carrier in ("American Integrity"))
then
    HO3AnimalLiability.clear();
    HO3AnimalLiability.add("Available - $50 ; Coverage - "+c.getCoverageE());
end

rule "carrier for which $25 and sublimit of $50000 is available"
when
    AnimalLiability(carrier in ("American Strategic","Monarch","Cabrillo","FedNat","Heritage","United"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Available - $25 ; Sublimit - $50,000");
end

rule "carrier for which $25 and sublimit of $25000 is available"
when
    AnimalLiability(carrier in ("Centauri","Edison","Florida Peninsula","Southern Oak","Velocity","Bankers"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Available - $25 ; Sublimit - $25,000");
end

rule "carrier for which $50 and sublimit of $50000 is available"
when
    AnimalLiability(carrier in ("Olympus","Prepared","St. Johns"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Available - $50 ; Sublimit - $50,000");
end

rule "carrier for which $30 and sublimit of $25000 is available"
when
    AnimalLiability(carrier in ("Frontline"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Available - $30 ; Sublimit - $25,000");
end

rule "carrier not available in Animal Liability"
when
    AnimalLiability(carrier in ("Homeowners Choice","Universal PC","Spinnaker"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Not Available");
end

rule "carrier for which $50 and sublimit of CoverageE is available"
when
    c:AnimalLiability(carrier in ("American Integrity"))
then
    HO6AnimalLiability.clear();
    HO6AnimalLiability.add("Available - $50 ; Coverage - "+c.getCoverageE());
end