package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Accreditedbuilder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String accredited;

   private java.lang.String accreditedSupplement;

   public Accreditedbuilder()
   {
   }

   public java.lang.String getAccredited()
   {
      return this.accredited;
   }

   public void setAccredited(java.lang.String accredited)
   {
      this.accredited = accredited;
   }

   public java.lang.String getAccreditedSupplement()
   {
      return this.accreditedSupplement;
   }

   public void setAccreditedSupplement(java.lang.String accreditedSupplement)
   {
      this.accreditedSupplement = accreditedSupplement;
   }

   public Accreditedbuilder(java.lang.String accredited,
         java.lang.String accreditedSupplement)
   {
      this.accredited = accredited;
      this.accreditedSupplement = accreditedSupplement;
   }

}