package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class alarmsystem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String alarmSystemType;

   public alarmsystem()
   {
   }

   public java.lang.String getAlarmSystemType()
   {
      return this.alarmSystemType;
   }

   public void setAlarmSystemType(java.lang.String alarmSystemType)
   {
      this.alarmSystemType = alarmSystemType;
   }

   public alarmsystem(java.lang.String alarmSystemType)
   {
      this.alarmSystemType = alarmSystemType;
   }

}