package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AnimalLiability implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carrierList;

   private java.lang.String coverageE;

   public AnimalLiability()
   {
   }

   public java.lang.String getCarrierList()
   {
      return this.carrierList;
   }

   public void setCarrierList(java.lang.String carrierList)
   {
      this.carrierList = carrierList;
   }

   public java.lang.String getCoverageE()
   {
      return this.coverageE;
   }

   public void setCoverageE(java.lang.String coverageE)
   {
      this.coverageE = coverageE;
   }

   public AnimalLiability(java.lang.String carrierList, java.lang.String coverageE)
   {
      this.carrierList = carrierList;
      this.coverageE = coverageE;
   }

}