package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Animal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String animals;

   public Animal()
   {
   }

   public java.lang.String getAnimals()
   {
      return this.animals;
   }

   public void setAnimals(java.lang.String animals)
   {
      this.animals = animals;
   }

   public Animal(java.lang.String animals)
   {
      this.animals = animals;
   }

}