package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DwellingLimit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String formType;
   private java.lang.String county;

   private java.lang.Integer yearBuilt;

   public DwellingLimit()
   {
   }

   public java.lang.String getFormType()
   {
      return this.formType;
   }

   public void setFormType(java.lang.String formType)
   {
      this.formType = formType;
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public DwellingLimit(java.lang.String formType, java.lang.String county,
         java.lang.Integer yearBuilt)
   {
      this.formType = formType;
      this.county = county;
      this.yearBuilt = yearBuilt;
   }

}