package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EquipmentBreakdown implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carrier;

   public EquipmentBreakdown()
   {
   }

   public java.lang.String getCarrier()
   {
      return this.carrier;
   }

   public void setCarrier(java.lang.String carrier)
   {
      this.carrier = carrier;
   }

   public EquipmentBreakdown(java.lang.String carrier)
   {
      this.carrier = carrier;
   }

}