package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FedNatMonarchOverrideFilter implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carrier;
   private java.lang.String county;
   private java.lang.Integer yearBuilt;
   private java.lang.Integer dwellingCoverage;

   public FedNatMonarchOverrideFilter()
   {
   }

   public java.lang.String getCarrier()
   {
      return this.carrier;
   }

   public void setCarrier(java.lang.String carrier)
   {
      this.carrier = carrier;
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.Integer getDwellingCoverage()
   {
      return this.dwellingCoverage;
   }

   public void setDwellingCoverage(java.lang.Integer dwellingCoverage)
   {
      this.dwellingCoverage = dwellingCoverage;
   }

   public FedNatMonarchOverrideFilter(java.lang.String carrier,
         java.lang.String county, java.lang.Integer yearBuilt,
         java.lang.Integer dwellingCoverage)
   {
      this.carrier = carrier;
      this.county = county;
      this.yearBuilt = yearBuilt;
      this.dwellingCoverage = dwellingCoverage;
   }

}
