package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FloodFirmDates implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String county;

   public FloodFirmDates()
   {
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public FloodFirmDates(java.lang.String county)
   {
      this.county = county;
   }

}
