package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FoundationPolicy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String foundation;
   private java.lang.Integer yearBuilt;

   public FoundationPolicy()
   {
   }

   public java.lang.String getFoundation()
   {
      return this.foundation;
   }

   public void setFoundation(java.lang.String foundation)
   {
      this.foundation = foundation;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public FoundationPolicy(java.lang.String foundation,
         java.lang.Integer yearBuilt)
   {
      this.foundation = foundation;
      this.yearBuilt = yearBuilt;
   }

}