package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineRoofTypeMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofType;

   public FrontlineRoofTypeMapping()
   {
   }

   public java.lang.String getRoofType()
   {
      return this.roofType;
   }

   public void setRoofType(java.lang.String roofType)
   {
      this.roofType = roofType;
   }

   public FrontlineRoofTypeMapping(java.lang.String roofType)
   {
      this.roofType = roofType;
   }

}
