package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineDogBreedMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dogBreed;

   public FrontlineDogBreedMapping()
   {
   }

   public java.lang.String getDogBreed()
   {
      return this.dogBreed;
   }

   public void setDogBreed(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

   public FrontlineDogBreedMapping(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

}
