package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineRoofWallConnectTypeMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofWallConnect;

   public FrontlineRoofWallConnectTypeMapping()
   {
   }

   public java.lang.String getRoofWallConnect()
   {
      return this.roofWallConnect;
   }

   public void setRoofWallConnect(java.lang.String roofWallConnect)
   {
      this.roofWallConnect = roofWallConnect;
   }

   public FrontlineRoofWallConnectTypeMapping(java.lang.String roofWallConnect)
   {
      this.roofWallConnect = roofWallConnect;
   }

}
