package org.brms.hhinsurance;
import java.util.HashMap;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String policyWriterFirstName;
   private java.lang.String policyWriterLastName;
   private HashMap<String,HashMap<String,Object>> quoterushData; 

   private java.lang.Boolean status;

   private java.lang.String uniqueIdentifier;

   private java.lang.String securityToken;

   private java.lang.Boolean hasFloodPolicy;

   public FrontlineMapping()
   {
   }
   
    public HashMap<String,HashMap<String,Object>> getQuoterushData()
   {
      return this.quoterushData;
   }


 public void setQuoterushData(HashMap<String,HashMap<String,Object>> quoterushData)
   {
      this.quoterushData = quoterushData;
   }

   public java.lang.String getPolicyWriterFirstName()
   {
      return this.policyWriterFirstName;
   }

   public void setPolicyWriterFirstName(java.lang.String policyWriterFirstName)
   {
      this.policyWriterFirstName = policyWriterFirstName;
   }

   public java.lang.String getPolicyWriterLastName()
   {
      return this.policyWriterLastName;
   }

   public void setPolicyWriterLastName(java.lang.String policyWriterLastName)
   {
      this.policyWriterLastName = policyWriterLastName;
   }

   public java.lang.Boolean getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Boolean status)
   {
      this.status = status;
   }

   public java.lang.String getUniqueIdentifier()
   {
      return this.uniqueIdentifier;
   }

   public void setUniqueIdentifier(java.lang.String uniqueIdentifier)
   {
      this.uniqueIdentifier = uniqueIdentifier;
   }

   public java.lang.String getSecurityToken()
   {
      return this.securityToken;
   }

   public void setSecurityToken(java.lang.String securityToken)
   {
      this.securityToken = securityToken;
   }

   public java.lang.Boolean getHasFloodPolicy()
   {
      return this.hasFloodPolicy;
   }

   public void setHasFloodPolicy(java.lang.Boolean hasFloodPolicy)
   {
      this.hasFloodPolicy = hasFloodPolicy;
   }

   public FrontlineMapping(java.lang.String policyWriterFirstName,
         java.lang.String policyWriterLastName, java.lang.Boolean status,
         java.lang.String uniqueIdentifier, java.lang.String securityToken,
         java.lang.Boolean hasFloodPolicy)
   {
      this.policyWriterFirstName = policyWriterFirstName;
      this.policyWriterLastName = policyWriterLastName;
      this.status = status;
      this.uniqueIdentifier = uniqueIdentifier;
      this.securityToken = securityToken;
      this.hasFloodPolicy = hasFloodPolicy;
   }

}