package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class gatedcommunity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String securityType;

   public gatedcommunity()
   {
   }

   public java.lang.String getSecurityType()
   {
      return this.securityType;
   }

   public void setSecurityType(java.lang.String securityType)
   {
      this.securityType = securityType;
   }

   public gatedcommunity(java.lang.String securityType)
   {
      this.securityType = securityType;
   }

}