package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HomeOwnersAssociation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String homeOwnersAsso;

   public HomeOwnersAssociation()
   {
   }

   public java.lang.String getHomeOwnersAsso()
   {
      return this.homeOwnersAsso;
   }

   public void setHomeOwnersAsso(java.lang.String homeOwnersAsso)
   {
      this.homeOwnersAsso = homeOwnersAsso;
   }

   public HomeOwnersAssociation(java.lang.String homeOwnersAsso)
   {
      this.homeOwnersAsso = homeOwnersAsso;
   }

}