package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMIHomeStyle implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String buildQuality;

   public MMIHomeStyle()
   {
   }

   public java.lang.String getBuildQuality()
   {
      return this.buildQuality;
   }

   public void setBuildQuality(java.lang.String buildQuality)
   {
      this.buildQuality = buildQuality;
   }

   public MMIHomeStyle(java.lang.String buildQuality)
   {
      this.buildQuality = buildQuality;
   }

}