package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMIRoofMaterial implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofCover;

   public MMIRoofMaterial()
   {
   }

   public java.lang.String getRoofCover()
   {
      return this.roofCover;
   }

   public void setRoofCover(java.lang.String roofCover)
   {
      this.roofCover = roofCover;
   }

   public MMIRoofMaterial(java.lang.String roofCover)
   {
      this.roofCover = roofCover;
   }

}