package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMIWallConstruction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String wallConstruction;

   public MMIWallConstruction()
   {
   }

   public java.lang.String getWallConstruction()
   {
      return this.wallConstruction;
   }

   public void setWallConstruction(java.lang.String wallConstruction)
   {
      this.wallConstruction = wallConstruction;
   }

   public MMIWallConstruction(java.lang.String wallConstruction)
   {
      this.wallConstruction = wallConstruction;
   }

}