package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Occupancy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String occupied;

   public Occupancy()
   {
   }

   public java.lang.String getOccupied()
   {
      return this.occupied;
   }

   public void setOccupied(java.lang.String occupied)
   {
      this.occupied = occupied;
   }

   public Occupancy(java.lang.String occupied)
   {
      this.occupied = occupied;
   }

}