package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OtherStructure implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String hasGarage;
   private java.lang.String garageStyle;
   private java.lang.Integer reConstructionValue;

   private Integer coverageA;

   public OtherStructure()
   {
   }

   public java.lang.String getHasGarage()
   {
      return this.hasGarage;
   }

   public void setHasGarage(java.lang.String hasGarage)
   {
      this.hasGarage = hasGarage;
   }

   public java.lang.String getGarageStyle()
   {
      return this.garageStyle;
   }

   public void setGarageStyle(java.lang.String garageStyle)
   {
      this.garageStyle = garageStyle;
   }

   public java.lang.Integer getReConstructionValue()
   {
      return this.reConstructionValue;
   }

   public void setReConstructionValue(java.lang.Integer reConstructionValue)
   {
      this.reConstructionValue = reConstructionValue;
   }

   public java.lang.Integer getCoverageA()
   {
      return this.coverageA;
   }

   public void setCoverageA(java.lang.Integer coverageA)
   {
      this.coverageA = coverageA;
   }

   public OtherStructure(java.lang.String hasGarage, java.lang.String garageStyle,
         java.lang.Integer reConstructionValue, java.lang.Integer coverageA)
   {
      this.hasGarage = hasGarage;
      this.garageStyle = garageStyle;
      this.reConstructionValue = reConstructionValue;
      this.coverageA = coverageA;
   }

}