package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonalInjury implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carrierList;

   public PersonalInjury()
   {
   }

   public java.lang.String getCarrierList()
   {
      return this.carrierList;
   }

   public void setCarrierList(java.lang.String carrierList)
   {
      this.carrierList = carrierList;
   }

   public PersonalInjury(java.lang.String carrierList)
   {
      this.carrierList = carrierList;
   }

}