package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class poolScreenedEnclosure implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String screendEnclosure;

   private java.lang.String hasPool;

   public poolScreenedEnclosure()
   {
   }

   public java.lang.String getScreendEnclosure()
   {
      return this.screendEnclosure;
   }

   public void setScreendEnclosure(java.lang.String screendEnclosure)
   {
      this.screendEnclosure = screendEnclosure;
   }

   public java.lang.String getHasPool()
   {
      return this.hasPool;
   }

   public void setHasPool(java.lang.String hasPool)
   {
      this.hasPool = hasPool;
   }

   public poolScreenedEnclosure(java.lang.String screendEnclosure,
         java.lang.String hasPool)
   {
      this.screendEnclosure = screendEnclosure;
      this.hasPool = hasPool;
   }

}