package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofShapeHip implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String percentageOfRoofShape;
   private java.lang.String roof;

   public RoofShapeHip()
   {
   }

   public java.lang.String getPercentageOfRoofShape()
   {
      return this.percentageOfRoofShape;
   }

   public void setPercentageOfRoofShape(java.lang.String percentageOfRoofShape)
   {
      this.percentageOfRoofShape = percentageOfRoofShape;
   }

   public java.lang.String getRoof()
   {
      return this.roof;
   }

   public void setRoof(java.lang.String roof)
   {
      this.roof = roof;
   }

   public RoofShapeHip(java.lang.String percentageOfRoofShape,
         java.lang.String roof)
   {
      this.percentageOfRoofShape = percentageOfRoofShape;
      this.roof = roof;
   }

}