package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScreenedEnclosure implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carrier;

   private java.lang.String screenedEnclosureCoverage;

   public ScreenedEnclosure()
   {
   }

   public java.lang.String getCarrier()
   {
      return this.carrier;
   }

   public void setCarrier(java.lang.String carrier)
   {
      this.carrier = carrier;
   }

   public java.lang.String getScreenedEnclosureCoverage()
   {
      return this.screenedEnclosureCoverage;
   }

   public void setScreenedEnclosureCoverage(
         java.lang.String screenedEnclosureCoverage)
   {
      this.screenedEnclosureCoverage = screenedEnclosureCoverage;
   }

   public ScreenedEnclosure(java.lang.String carrier,
         java.lang.String screenedEnclosureCoverage)
   {
      this.carrier = carrier;
      this.screenedEnclosureCoverage = screenedEnclosureCoverage;
   }

}