package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SecondOwner implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nameInsured;

   public SecondOwner()
   {
   }

   public java.lang.String getNameInsured()
   {
      return this.nameInsured;
   }

   public void setNameInsured(java.lang.String nameInsured)
   {
      this.nameInsured = nameInsured;
   }

   public SecondOwner(java.lang.String nameInsured)
   {
      this.nameInsured = nameInsured;
   }

}