package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SSConstructionType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String constructionType;
   private java.lang.String construction;

   public SSConstructionType()
   {
   }

   public java.lang.String getConstructionType()
   {
      return this.constructionType;
   }

   public void setConstructionType(java.lang.String constructionType)
   {
      this.constructionType = constructionType;
   }

   public java.lang.String getConstruction()
   {
      return this.construction;
   }

   public void setConstruction(java.lang.String construction)
   {
      this.construction = construction;
   }

   public SSConstructionType(java.lang.String constructionType,
         java.lang.String construction)
   {
      this.constructionType = constructionType;
      this.construction = construction;
   }

}