package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SSHomeStyle implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String stories;
   private java.lang.String structureType;

   public SSHomeStyle()
   {
   }

   public java.lang.String getStories()
   {
      return this.stories;
   }

   public void setStories(java.lang.String stories)
   {
      this.stories = stories;
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public SSHomeStyle(java.lang.String stories, java.lang.String structureType)
   {
      this.stories = stories;
      this.structureType = structureType;
   }

}