package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SSPoolFence implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String poolFencedOrScreened;
   private java.lang.String pool;

   public SSPoolFence()
   {
   }

   public java.lang.String getPoolFencedOrScreened()
   {
      return this.poolFencedOrScreened;
   }

   public void setPoolFencedOrScreened(java.lang.String poolFencedOrScreened)
   {
      this.poolFencedOrScreened = poolFencedOrScreened;
   }

   public java.lang.String getPool()
   {
      return this.pool;
   }

   public void setPool(java.lang.String pool)
   {
      this.pool = pool;
   }

   public SSPoolFence(java.lang.String poolFencedOrScreened,
         java.lang.String pool)
   {
      this.poolFencedOrScreened = poolFencedOrScreened;
      this.pool = pool;
   }

}