package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StructureType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer stories;

   private java.lang.String structureType;

   public StructureType()
   {
   }

   public java.lang.Integer getStories()
   {
      return this.stories;
   }

   public void setStories(java.lang.Integer stories)
   {
      this.stories = stories;
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public StructureType(java.lang.Integer stories, java.lang.String structureType)
   {
      this.stories = stories;
      this.structureType = structureType;
   }

}