package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TypeOfConstruction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String constructionRatio;
   private java.lang.String constructionType;
   private java.lang.String masonryConstruction;
   private java.lang.String frameConstruction;

   public TypeOfConstruction()
   {
   }

   public java.lang.String getConstructionRatio()
   {
      return this.constructionRatio;
   }

   public void setConstructionRatio(java.lang.String constructionRatio)
   {
      this.constructionRatio = constructionRatio;
   }

   public java.lang.String getConstructionType()
   {
      return this.constructionType;
   }

   public void setConstructionType(java.lang.String constructionType)
   {
      this.constructionType = constructionType;
   }

   public java.lang.String getMasonryConstruction()
   {
      return this.masonryConstruction;
   }

   public void setMasonryConstruction(java.lang.String masonryConstruction)
   {
      this.masonryConstruction = masonryConstruction;
   }

   public java.lang.String getFrameConstruction()
   {
      return this.frameConstruction;
   }

   public void setFrameConstruction(java.lang.String frameConstruction)
   {
      this.frameConstruction = frameConstruction;
   }

   public TypeOfConstruction(java.lang.String constructionRatio,
         java.lang.String constructionType,
         java.lang.String masonryConstruction, java.lang.String frameConstruction)
   {
      this.constructionRatio = constructionRatio;
      this.constructionType = constructionType;
      this.masonryConstruction = masonryConstruction;
      this.frameConstruction = frameConstruction;
   }

}