package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WindOverride implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofWallConnection;
   private java.lang.String awareClips;
   private java.lang.String openingProtection;
   private java.lang.String selectionAOrB;
   private java.lang.String subSelectionA;
   private java.lang.String subSelectionB;
   private java.lang.String awareShutters;
   private java.lang.String protectedWindows;

   private java.lang.String questionFour;

   private java.lang.String questionSeven;

   private java.lang.String questionSix;

   private java.lang.String questionThree;

   public WindOverride()
   {
   }

   public java.lang.String getRoofWallConnection()
   {
      return this.roofWallConnection;
   }

   public void setRoofWallConnection(java.lang.String roofWallConnection)
   {
      this.roofWallConnection = roofWallConnection;
   }

   public java.lang.String getAwareClips()
   {
      return this.awareClips;
   }

   public void setAwareClips(java.lang.String awareClips)
   {
      this.awareClips = awareClips;
   }

   public java.lang.String getOpeningProtection()
   {
      return this.openingProtection;
   }

   public void setOpeningProtection(java.lang.String openingProtection)
   {
      this.openingProtection = openingProtection;
   }

   public java.lang.String getSelectionAOrB()
   {
      return this.selectionAOrB;
   }

   public void setSelectionAOrB(java.lang.String selectionAOrB)
   {
      this.selectionAOrB = selectionAOrB;
   }

   public java.lang.String getSubSelectionA()
   {
      return this.subSelectionA;
   }

   public void setSubSelectionA(java.lang.String subSelectionA)
   {
      this.subSelectionA = subSelectionA;
   }

   public java.lang.String getSubSelectionB()
   {
      return this.subSelectionB;
   }

   public void setSubSelectionB(java.lang.String subSelectionB)
   {
      this.subSelectionB = subSelectionB;
   }

   public java.lang.String getAwareShutters()
   {
      return this.awareShutters;
   }

   public void setAwareShutters(java.lang.String awareShutters)
   {
      this.awareShutters = awareShutters;
   }

   public java.lang.String getProtectedWindows()
   {
      return this.protectedWindows;
   }

   public void setProtectedWindows(java.lang.String protectedWindows)
   {
      this.protectedWindows = protectedWindows;
   }

   public java.lang.String getQuestionFour()
   {
      return this.questionFour;
   }

   public void setQuestionFour(java.lang.String questionFour)
   {
      this.questionFour = questionFour;
   }

   public java.lang.String getQuestionSeven()
   {
      return this.questionSeven;
   }

   public void setQuestionSeven(java.lang.String questionSeven)
   {
      this.questionSeven = questionSeven;
   }

   public java.lang.String getQuestionSix()
   {
      return this.questionSix;
   }

   public void setQuestionSix(java.lang.String questionSix)
   {
      this.questionSix = questionSix;
   }

   public java.lang.String getQuestionThree()
   {
      return this.questionThree;
   }

   public void setQuestionThree(java.lang.String questionThree)
   {
      this.questionThree = questionThree;
   }

   public WindOverride(java.lang.String roofWallConnection,
         java.lang.String awareClips, java.lang.String openingProtection,
         java.lang.String selectionAOrB, java.lang.String subSelectionA,
         java.lang.String subSelectionB, java.lang.String awareShutters,
         java.lang.String protectedWindows, java.lang.String questionFour,
         java.lang.String questionSeven, java.lang.String questionSix,
         java.lang.String questionThree)
   {
      this.roofWallConnection = roofWallConnection;
      this.awareClips = awareClips;
      this.openingProtection = openingProtection;
      this.selectionAOrB = selectionAOrB;
      this.subSelectionA = subSelectionA;
      this.subSelectionB = subSelectionB;
      this.awareShutters = awareShutters;
      this.protectedWindows = protectedWindows;
      this.questionFour = questionFour;
      this.questionSeven = questionSeven;
      this.questionSix = questionSix;
      this.questionThree = questionThree;
   }

}