package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WindMitigation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String windMitigation;
   private java.lang.String suplement2;
   private java.lang.String suplement3;
   private java.lang.String suplement6;
   private java.lang.String suplement1;

   public WindMitigation()
   {
   }

   public java.lang.String getWindMitigation()
   {
      return this.windMitigation;
   }

   public void setWindMitigation(java.lang.String windMitigation)
   {
      this.windMitigation = windMitigation;
   }

   public java.lang.String getSuplement2()
   {
      return this.suplement2;
   }

   public void setSuplement2(java.lang.String suplement2)
   {
      this.suplement2 = suplement2;
   }

   public java.lang.String getSuplement3()
   {
      return this.suplement3;
   }

   public void setSuplement3(java.lang.String suplement3)
   {
      this.suplement3 = suplement3;
   }

   public java.lang.String getSuplement6()
   {
      return this.suplement6;
   }

   public void setSuplement6(java.lang.String suplement6)
   {
      this.suplement6 = suplement6;
   }

   public java.lang.String getSuplement1()
   {
      return this.suplement1;
   }

   public void setSuplement1(java.lang.String suplement1)
   {
      this.suplement1 = suplement1;
   }

   public WindMitigation(java.lang.String windMitigation,
         java.lang.String suplement2, java.lang.String suplement3,
         java.lang.String suplement6, java.lang.String suplement1)
   {
      this.windMitigation = windMitigation;
      this.suplement2 = suplement2;
      this.suplement3 = suplement3;
      this.suplement6 = suplement6;
      this.suplement1 = suplement1;
   }

}