package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WindMitigationIfNo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String supplement4;

   private java.lang.String supplement5;

   public WindMitigationIfNo()
   {
   }

   public java.lang.String getSupplement4()
   {
      return this.supplement4;
   }

   public void setSupplement4(java.lang.String supplement4)
   {
      this.supplement4 = supplement4;
   }

   public java.lang.String getSupplement5()
   {
      return this.supplement5;
   }

   public void setSupplement5(java.lang.String supplement5)
   {
      this.supplement5 = supplement5;
   }

   public WindMitigationIfNo(java.lang.String supplement4,
         java.lang.String supplement5)
   {
      this.supplement4 = supplement4;
      this.supplement5 = supplement5;
   }

}