package org.brms.hhinsurance;

import java.util.Calendar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgeOfHomeCarrier implements java.io.Serializable
{

   Calendar now = Calendar.getInstance();
   public int year = now.get(Calendar.YEAR);
   static final long serialVersionUID = 1L;

   private java.lang.Integer yearBuilt;

   public AgeOfHomeCarrier()
   {
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public AgeOfHomeCarrier(java.util.Calendar now, int year,
         java.lang.Integer yearBuilt)
   {
      this.now = now;
      this.year = year;
      this.yearBuilt = yearBuilt;
   }

}