package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgeOfHome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String ifCertified;

   public AgeOfHome()
   {
   }

   public java.lang.String getIfCertified()
   {
      return this.ifCertified;
   }

   public void setIfCertified(java.lang.String ifCertified)
   {
      this.ifCertified = ifCertified;
   }

   public AgeOfHome(java.lang.String ifCertified)
   {
      this.ifCertified = ifCertified;
   }

}