package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AnimalLiability implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String coverageE;

   private java.lang.String carrier;

   public AnimalLiability()
   {
   }

   public java.lang.String getCoverageE()
   {
      return this.coverageE;
   }

   public void setCoverageE(java.lang.String coverageE)
   {
      this.coverageE = coverageE;
   }

   public java.lang.String getCarrier()
   {
      return this.carrier;
   }

   public void setCarrier(java.lang.String carrier)
   {
      this.carrier = carrier;
   }

   public AnimalLiability(java.lang.String coverageE, java.lang.String carrier)
   {
      this.coverageE = coverageE;
      this.carrier = carrier;
   }

}