package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContentsValuation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String personalPropertyReplacementCost;

   public ContentsValuation()
   {
   }

   public java.lang.String getPersonalPropertyReplacementCost()
   {
      return this.personalPropertyReplacementCost;
   }

   public void setPersonalPropertyReplacementCost(
         java.lang.String personalPropertyReplacementCost)
   {
      this.personalPropertyReplacementCost = personalPropertyReplacementCost;
   }

   public ContentsValuation(java.lang.String personalPropertyReplacementCost)
   {
      this.personalPropertyReplacementCost = personalPropertyReplacementCost;
   }

}