package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String structureType;
   private java.lang.String occupancyType;
   private java.lang.String planToRent;
   private java.lang.String townType;
   private java.lang.Integer HOAfee;

   public FormType()
   {
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public java.lang.String getOccupancyType()
   {
      return this.occupancyType;
   }

   public void setOccupancyType(java.lang.String occupancyType)
   {
      this.occupancyType = occupancyType;
   }

   public java.lang.String getPlanToRent()
   {
      return this.planToRent;
   }

   public void setPlanToRent(java.lang.String planToRent)
   {
      this.planToRent = planToRent;
   }

   public java.lang.String getTownType()
   {
      return this.townType;
   }

   public void setTownType(java.lang.String townType)
   {
      this.townType = townType;
   }

   public java.lang.Integer getHOAfee()
   {
      return this.HOAfee;
   }

   public void setHOAfee(java.lang.Integer HOAfee)
   {
      this.HOAfee = HOAfee;
   }

   public FormType(java.lang.String structureType,
         java.lang.String occupancyType, java.lang.String planToRent,
         java.lang.String townType, java.lang.Integer HOAfee)
   {
      this.structureType = structureType;
      this.occupancyType = occupancyType;
      this.planToRent = planToRent;
      this.townType = townType;
      this.HOAfee = HOAfee;
   }

}