package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontineGatedGuardedCommunityMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String gatedCommunity;
   private java.lang.Boolean isGuardedCommunity;
   private java.lang.Boolean isGatedCommunity;

   public FrontineGatedGuardedCommunityMapping()
   {
   }

   public java.lang.String getGatedCommunity()
   {
      return this.gatedCommunity;
   }

   public void setGatedCommunity(java.lang.String gatedCommunity)
   {
      this.gatedCommunity = gatedCommunity;
   }

   public java.lang.Boolean getIsGuardedCommunity()
   {
      return this.isGuardedCommunity;
   }

   public void setIsGuardedCommunity(java.lang.Boolean isGuardedCommunity)
   {
      this.isGuardedCommunity = isGuardedCommunity;
   }

   public java.lang.Boolean getIsGatedCommunity()
   {
      return this.isGatedCommunity;
   }

   public void setIsGatedCommunity(java.lang.Boolean isGatedCommunity)
   {
      this.isGatedCommunity = isGatedCommunity;
   }

   public FrontineGatedGuardedCommunityMapping(java.lang.String gatedCommunity,
         java.lang.Boolean isGuardedCommunity, java.lang.Boolean isGatedCommunity)
   {
      this.gatedCommunity = gatedCommunity;
      this.isGuardedCommunity = isGuardedCommunity;
      this.isGatedCommunity = isGatedCommunity;
   }

}
