package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineFoundationTypeMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String foundation;

   public FrontlineFoundationTypeMapping()
   {
   }

   public java.lang.String getFoundation()
   {
      return this.foundation;
   }

   public void setFoundation(java.lang.String foundation)
   {
      this.foundation = foundation;
   }

   public FrontlineFoundationTypeMapping(java.lang.String foundation)
   {
      this.foundation = foundation;
   }

}
