package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FrontlineConstructionTypeMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String constructionType;

   private java.lang.String frameConstructionType;

   public FrontlineConstructionTypeMapping()
   {
   }

   public java.lang.String getConstructionType()
   {
      return this.constructionType;
   }

   public void setConstructionType(java.lang.String constructionType)
   {
      this.constructionType = constructionType;
   }

   public java.lang.String getFrameConstructionType()
   {
      return this.frameConstructionType;
   }

   public void setFrameConstructionType(java.lang.String frameConstructionType)
   {
      this.frameConstructionType = frameConstructionType;
   }

   public FrontlineConstructionTypeMapping(java.lang.String constructionType,
         java.lang.String frameConstructionType)
   {
      this.constructionType = constructionType;
      this.frameConstructionType = frameConstructionType;
   }

}
