package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MMIStructureType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String structureType;

   public MMIStructureType()
   {
   }

   public java.lang.String getStructureType()
   {
      return this.structureType;
   }

   public void setStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

   public MMIStructureType(java.lang.String structureType)
   {
      this.structureType = structureType;
   }

}