package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OpenClosePolicy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String open;

   public OpenClosePolicy()
   {
   }

   public java.lang.String getOpen()
   {
      return this.open;
   }

   public void setOpen(java.lang.String open)
   {
      this.open = open;
   }

   public OpenClosePolicy(java.lang.String open)
   {
      this.open = open;
   }

}