package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PlumbPolicy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer yearBuilt;
   private java.lang.String plumbingType;

   public PlumbPolicy()
   {
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.String getPlumbingType()
   {
      return this.plumbingType;
   }

   public void setPlumbingType(java.lang.String plumbingType)
   {
      this.plumbingType = plumbingType;
   }

   public PlumbPolicy(java.lang.Integer yearBuilt, java.lang.String plumbingType)
   {
      this.yearBuilt = yearBuilt;
      this.plumbingType = plumbingType;
   }

}