package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofMaterialHazard implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofMaterialType;

   public RoofMaterialHazard()
   {
   }

   public java.lang.String getRoofMaterialType()
   {
      return this.roofMaterialType;
   }

   public void setRoofMaterialType(java.lang.String roofMaterialType)
   {
      this.roofMaterialType = roofMaterialType;
   }

   public RoofMaterialHazard(java.lang.String roofMaterialType)
   {
      this.roofMaterialType = roofMaterialType;
   }

}