package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofMaterialName implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofMaterial;

   public RoofMaterialName()
   {
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   public RoofMaterialName(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

}