package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoofPolicy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer age;
   private java.lang.String roofMaterial;

   public RoofPolicy()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getRoofMaterial()
   {
      return this.roofMaterial;
   }

   public void setRoofMaterial(java.lang.String roofMaterial)
   {
      this.roofMaterial = roofMaterial;
   }

   public RoofPolicy(java.lang.Integer age, java.lang.String roofMaterial)
   {
      this.age = age;
      this.roofMaterial = roofMaterial;
   }

}