package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SterlingBuildingDiagramMapping implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String foundation;
   private java.lang.String foundationType;
   private Integer yearBuilt;

   private java.lang.String buildingDiagram;

   public SterlingBuildingDiagramMapping()
   {
   }

   public java.lang.String getFoundation()
   {
      return this.foundation;
   }

   public void setFoundation(java.lang.String foundation)
   {
      this.foundation = foundation;
   }

   public java.lang.String getFoundationType()
   {
      return this.foundationType;
   }

   public void setFoundationType(java.lang.String foundationType)
   {
      this.foundationType = foundationType;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.String getBuildingDiagram()
   {
      return this.buildingDiagram;
   }

   public void setBuildingDiagram(java.lang.String buildingDiagram)
   {
      this.buildingDiagram = buildingDiagram;
   }

   public SterlingBuildingDiagramMapping(java.lang.String foundation,
         java.lang.String foundationType, java.lang.Integer yearBuilt,
         java.lang.String buildingDiagram)
   {
      this.foundation = foundation;
      this.foundationType = foundationType;
      this.yearBuilt = yearBuilt;
      this.buildingDiagram = buildingDiagram;
   }

}
