package org.brms.hhinsurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValueOfHome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer coverageA;

   public ValueOfHome()
   {
   }

   public java.lang.Integer getCoverageA()
   {
      return this.coverageA;
   }

   public void setCoverageA(java.lang.Integer coverageA)
   {
      this.coverageA = coverageA;
   }

   public ValueOfHome(java.lang.Integer coverageA)
   {
      this.coverageA = coverageA;
   }

}