package org.brms.hhinsurance;
global java.util.List value;
global java.util.List key;

rule "if accredited builder is certified"
when
    AgeOfHome(ifCertified.equalsIgnoreCase("yes"))
then
    value.clear();
    key.clear();
    value.add(1);
    key.add("Built by certified builder");
end

rule "if accredited builder is not certified"
when
    AgeOfHome(ifCertified.equalsIgnoreCase("no"))
then
    value.clear();
    key.clear();
    key.add("Not built by a certified builder");
end

