package org.brms.hhinsurance;
global java.util.List value;
global java.util.List key;

rule "Check wether the structure is masonary"
    when
        Construction(constructionType=="Masonry")
    then
        value.clear();
        key.clear();
        value.add(1);
        key.add("Display: The construction type is masonry");
end

rule "Check wether the structure is frame"
    when
        Construction(constructionType=="Frame")
    then
        value.clear();
        key.clear();
        value.add(2);
        key.add("Display: The construction type is frame and display the ratio");
end

rule "Check wether the structure is Mixed-masonary"
    when
        Construction(constructionType=="Mixed Masonry-Frame")
    then
        value.clear();
        key.clear();
        value.add(3);
        key.add("Display: The construction type is Mixed masonry frame");
end

rule "if not Mixed-masonary"
    when
        Construction(constructionType=="Superior")
    then
        value.clear();
        key.clear();
        value.add(0);
        key.add("Display: The construction type is not Mixed masonry frame and don't display the ratio");
end