package org.brms.hhinsurance;
global java.util.List animalLiability;

rule "carrier for which $25 and sublimit of $50000 is available"
when
    AnimalLiability(carrierList in ("American Strategic","Monarch","Cabrillo","FedNat","Florida Specialty","Heritage","Service (SageSure","United"))
then
    animalLiability.clear();
    animalLiability.add("Available - $25 ; Sublimit - $50,000");
end

rule "carrier for which $25 and sublimit of $25000 is available"
when
    AnimalLiability(carrierList in ("Anchor","Bankers","Centauri","Edison","Florida Peninsula","Southern Oak","Velocity"))
then
    animalLiability.clear();
    animalLiability.add("Available - $25 ; Sublimit - $25,000");
end

rule "carrier for which $50 and sublimit of $50000 is available"
when
    AnimalLiability(carrierList in ("Olympus","Prepared","St. Johns"))
then
    animalLiability.clear();
    animalLiability.add("Available - $50 ; Sublimit - $50,000");
end

rule "carrier which is included and sublimit of $50000 is available"
when
    AnimalLiability(carrierList in ("Swyfft"))
then
    animalLiability.clear();
    animalLiability.add("Included ; Sublimit - $50,000");
end

rule "carrier for which $30 and sublimit of $25000 is available"
when
    AnimalLiability(carrierList in ("Frontline"))
then
    animalLiability.clear();
    animalLiability.add("Available - $30 ; Sublimit - $25,000");
end

rule "carrier not available in Animal Liability"
when
    AnimalLiability(carrierList in ("GeoVera","Homeowners Choice","TypTap Home","Universal PC"))
then
    animalLiability.clear();
    animalLiability.add("Not Available");
end

rule "carrier for which $25 and sublimit of CoverageE is available"
when
    c:AnimalLiability(carrierList in ("Western World"))
then
    animalLiability.clear();
    animalLiability.add("Available - $25 ; Coverage - "+c.getCoverageE());
end

rule "carrier for which $50 and sublimit of CoverageE is available"
when
    c:AnimalLiability(carrierList in ("American Integrity"))
then
    animalLiability.clear();
    animalLiability.add("Available - $50 ; Coverage - "+c.getCoverageE());
end