package org.brms.hhinsurance;
global java.util.List contentValuation;

rule "if PersonalPropertyReplacementCost is 0"
when
    ContentsValuation(personalPropertyReplacementCost == "0")
then
    contentValuation.clear();
    contentValuation.add("Actual Cash Value");
end

rule "if PersonalPropertyReplacementCost is 1"
when
    ContentsValuation(personalPropertyReplacementCost == "1")
then
    contentValuation.clear();
    contentValuation.add("Replacement Cost");
end
    
    
