package org.brms.hhinsurance;
global java.util.List roofShape;
global java.util.List roofHipPercent;

rule "Roof Shape : Hip and combination"
when 
    RoofShapeHip(roof.equals("hip") || roof.equals("combination"))
then
    drools.setFocus("RoofShapePercentage");
end

rule "Roof shape percentage:50%hip/50%gable"
ruleflow-group "RoofShapePercentage"
when
    RoofShapeHip(percentageOfRoofShape=="50%hip/50%gable" || percentageOfRoofShape=="50%hip/50%flat")
then
    roofShape.clear();
    roofHipPercent.clear();
    roofShape.add("Gable");
    roofHipPercent.add("N/A");
end

rule "Roof shape percentage:75%hip/25%gable"
ruleflow-group "RoofShapePercentage"
when
    RoofShapeHip(percentageOfRoofShape=="75%hip/25%gable" || percentageOfRoofShape=="75%hip/25%flat")
then
    roofShape.clear();
    roofHipPercent.clear();
    roofShape.add("Gable");
    roofHipPercent.add("75%");
end

rule "Roof shape percentage:90%hip/10%gable"
ruleflow-group "RoofShapePercentage"
when
    RoofShapeHip(percentageOfRoofShape=="90%hip/10%gable" || percentageOfRoofShape=="100%hip")
then
    roofShape.clear();
    roofHipPercent.clear();
    roofShape.add("Hip");
    roofHipPercent.add("");
end

rule "Roof shape Gable, flat, other, unknown"
when 
    RoofShapeHip(roof != "hip" && roof != "combination")
then
    roofShape.clear();
    roofHipPercent.clear();
    roofShape.add("Gable");
    roofHipPercent.add("N/A");
end
