package org.brms.hhinsurance;
global java.util.List roofmaterial;

rule "check for Composite shingle"

when
    RoofMaterialName(roofMaterial.equals("3-Tab Shingle"))
then
    roofmaterial.clear();
    roofmaterial.add("Composite Shingle");
end

rule "check for Architectural shingle"

when
    RoofMaterialName(roofMaterial.equals("Architectural Shingles"))
then
    roofmaterial.clear();
    roofmaterial.add("Architectural Shingles");
end

rule "check for Metal"

when
    RoofMaterialName(roofMaterial.equals("Metal"))
then
    roofmaterial.clear();
    roofmaterial.add("Metal");
end

rule "check for Tile"

when
    RoofMaterialName(roofMaterial.equals("Tile"))
then
    roofmaterial.clear();
    roofmaterial.add("Tile");
end

rule "check for Tar and Gravel"

when
    RoofMaterialName(roofMaterial.equals("Tar And Gravel"))
then
    roofmaterial.clear();
    roofmaterial.add("Tar and Gravel");
end

rule "check for others"

when
    RoofMaterialName(roofMaterial in ("Other","Flat","Unknown"))
then
    roofmaterial.clear();
    roofmaterial.add("Other");
end