package org.brms.hhinsurance;
global java.util.List value;
global java.util.List key;

rule "Check whether you have a secured community"
    when
        Safety(securedCommunity=="yes")
    then
        value.clear();
        key.clear();
        value.add(1);
        key.add("Display:Have a secured community");
end

rule "Check if not a secured community"
    when
        Safety(securedCommunity=="no")
    then
        value.clear();
        key.clear();
        key.add("Display:no secured community");
end
