package org.brms.hhinsurance;
global java.util.List value;
global java.util.List key;

rule "Check whether Constructed before 2001"
    when
        YearOfConstruction(yearOfConstruction<2002)
    then
        value.clear();
        key.clear();
        value.add(1);
        key.add("Constructed on or before 2001");
end

rule "Check whether year of construction is less than 30 years"
    when
        YearOfConstruction(yearOfConstruction<(year-29))
    then
        value.clear();
        key.clear();
        value.add(2);
        key.add("Constructed before 30 years");
end

rule "Check whether constructed before 2001"
    when
        YearOfConstruction(yearOfConstruction==year)
    then
        value.clear();
        key.clear();
        value.add(3);
        key.add("Constructed in the current year");
    end

rule "Check whether constructed before 5 years"
    when
        YearOfConstruction(yearOfConstruction>(year-6)&&(yearOfConstruction!=year))
    then
        value.clear();
        key.clear();
        value.add(4);
        key.add("Constructed before 5 years from current year");
    end

rule "Check whether constructed between this years"
    when
        YearOfConstruction((yearOfConstruction>2001)&&(yearOfConstruction<(year-5)))
    then
        value.clear();
        key.clear();
        value.add(0);
        key.add("Dont display any options");
    end



